[project]
name = "PassTheATS"
version = "0.1.0"
description = "Minimalist Structure-Aware ATS Simulator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "scikit-learn",
    "pypdf",
    "python-docx",
    "spacy>=3.8.11",
    "en-core-web-sm",
]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
